# Generated by Django 6.0.7 on 2026-08-17 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_batch'),
        ('students', '0002_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='course_assignment',
            field=models.ForeignKey(blank=True, help_text='Set when attendance is marked by a teacher for a specific class.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.courseassignment'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('course_assignment__isnull', False)), fields=('student', 'course_assignment', 'date'), name='unique_course_attendance_per_day'),
        ),
    ]
